[package]
name = "android_ndk_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
jni = { version = "*"}
nalgebra = "0.29.0"

[lib]
crate-type = ["cdylib"] 