[package]
name = "autocxx1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "*"
autocxx = "*"

[build-dependencies]
autocxx-build = "*"
miette = { version = "*", features = ["fancy"] }